export { default as SplashScreen } from '../../screens/Common/SplashScreen';
export { default as ChangePasswordScreen } from '../../screens/Common/ChangePasswordScreen';
export { default as PrivacyPolicyScreen } from '../../screens/Common/PrivacyPolicyScreen';
export { default as BottomTabView } from '../../screens/Home/BottomTabView';
export { default as LoginScreen } from '../../screens/Login/LoginScreen';
export { default as OtpVerificationScreen } from '../../screens/Register/OtpVerificationScreen';
export { default as SignUpScreen } from '../../screens/Register/SignUpScreen';
export { default as SignUpSuccessScreen } from '../../screens/Register/SignUpSuccessScreen';
export { default as NotificationScreen } from '../../screens/Common/NotificationScreen';
